export const CHAT_SWITCH_VISIBLE = "CHAT_SWITCH_VISIBLE";
export const CHAT_ADD_MESSAGE = "CHAT_ADD_MESSAGE";
export const CHAT_ADD_UNREAD = "CHAT_ADD_UNREAD";
export const CHAT_MARK_AS_READ = "CHAT_MARK_AS_READ";