// Get PROFILE
export const PROFILE_GET_DATA = 'PROFILE_GET_DATA';
export const PROFILE_GET_DATA_SUCCESS = 'PROFILE_GET_DATA_SUCCESS';
export const PROFILE_GET_DATA_FAILURE = 'PROFILE_GET_DATA_FAILURE';