// Change language
export const SETTINGS_CHANGE_LANGUAGE = "SETTINGS_CHANGE_LANGUAGE";

// Devices
export const SETTINGS_AUDIO_DEVICES_LIST = "SETTINGS_AUDIO_DEVICES_LIST";
export const SETTINGS_AUDIO_DEVICE_SELECTED = "SETTINGS_AUDIO_DEVICE_SELECTED";
export const SETTINGS_AUDIO_DEVICES_SINK_LIST =
  "SETTINGS_AUDIO_DEVICES_SINK_LIST";
export const SETTINGS_AUDIO_DEVICE_SINK_SELECTED =
  "SETTINGS_AUDIO_DEVICE_SINK_SELECTED";
export const SETTINGS_VIDEO_DEVICES_LIST = "SETTINGS_VIDEO_DEVICES_LIST";
export const SETTINGS_VIDEO_DEVICE_SELECTED = "SETTINGS_VIDEO_DEVICE_SELECTED";
