// Conference data
export const CONFERENCE_ADD_DATA = "CONFERENCE_ADD_DATA";
export const CONFERECE_SHOW_LOADING = "CONFERECE_SHOW_LOADING";
export const CONFERECE_HIDE_LOADING = "CONFERECE_HIDE_LOADING";
export const CONFERECE_UPDATE_JOINED_DATA= "CONFERECE_UPDATE_JOINED_DATA";
export const CONFERECE_UPDATE_GENERAL_DATA= "CONFERECE_UPDATE_GENERAL_DATA";
// Media
export const CONFERENCE_SWITCH_CAMERA = "CONFERENCE_SWITCH_CAMERA";
export const CONFERENCE_SWITCH_MIC = "CONFERENCE_SWITCH_MIC";
export const CONFERENCE_SWITCH_SHARE = "CONFERENCE_SWITCH_SHARE";
// Peers
export const CONFERENCE_PEERS_UPDATE_LIST = "CONFERENCE_PEERS_UPDATE_LIST";
// Other people: connected or not
export const CONFERENCE_UPDATE_OTHER_PEOPLE = "CONFERENCE_UPDATE_OTHER_PEOPLE";
export const CONFERENCE_PEERS_ADD_PEER = "CONFERENCE_PEERS_ADD_PEER";
export const CONFERENCE_PEERS_REMOVE_PEER = "CONFERENCE_PEERS_REMOVE_PEER";