// Conference data
export const CONFERENCE_ADD_DATA = "CONFERENCE_ADD_DATA";
// Peers
export const CONFERENCE_PEERS_ADD = "CONFERENCE_PEERS_ADD";
export const CONFERENCE_PEERS_REMOVE = "CONFERENCE_PEERS_REMOVE";
