// Conference data
export const CONFERENCE_ADD_DATA = "CONFERENCE_ADD_DATA";
// Peers
export const CONFERENCE_PEERS_UPDATE_LIST = "CONFERENCE_PEERS_UPDATE_LIST";
export const CONFERENCE_PEERS_UPDATE_PEER_SETTINGS = "CONFERENCE_PEERS_UPDATE_PEER_SETTINGS";
export const CONFERENCE_PEERS_ADD_PEER = "CONFERENCE_PEERS_ADD_PEER";